<<<<<<< HEAD
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
=======
[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "line-profiler>=4.2.0",
    "matplotlib>=3.10.1",
    "memory-profiler>=0.61.0",
    "plotly>=6.0.1",
    "psycopg2-binary>=2.9.10",
]
>>>>>>> 06a5ef2 (Add CI/CD pipeline and example scripts for PyPerfOptimizer.  This includes automation, dashboard integration, and memory optimization examples.)
